<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.0" />
      <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.10" />
      <PackageReference Include="SQLitePCLRaw.core" Version="2.1.10" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Shutterings.db" />
      <Content Include="Shutterings.db">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
